#!/usr/bin/env python3
import os
import sys
import html
import plotly
import socket
import helpers

from analyzer import Analyzer
from termcolor import colored
from twython import Twython
from twython import TwythonAuthError, TwythonError, TwythonRateLimitError

def main():

    # ensure proper usage
    if len(sys.argv) != 2 or str(sys.argv[1])[0] != "@" :
        sys.exit("Usage: ./smile @word")

    # get user's tweets

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    tweets = helpers.get_user_timeline(sys.argv[1])
    if tweets == None:
        print("Error")
        return 1

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # calculate score
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{score} {text}". format(score = score, text = tweet), "green"))
        elif score < 0.0:
            print(colored("{score} {text}". format(score = score, text = tweet), "red"))
        else:
            print(colored("{score} {text}". format(score = score, text = tweet), "yellow"))

if __name__ == "__main__":
    main()
